### PR TITLE
Add use_common_time argument to MultipleSeries.to_pandas

### PR DESCRIPTION
**Pull request by MarcoGorelli**

### CODE REVIEW

**Review by CommonClimate — APPROVED** [review]
Wow, that is a lot simpler than I thought! So, the alignment to a common index happens automatically when a dataframe is created? That works well.  I think the default value for use_common_time should be `False`, so I made the change.

**Comment by CommonClimate** [comment]
So, right now the function call is `to_pandas(self, *args, use_common_time=False, **kwargs)`. I am not exactly clear why *args is coming before  `use_common_time`, and the order matters. Can you explain?

**Comment by MarcoGorelli** [comment]
Hey - sure, it's just that in Python, you need to put positional arguments before keyword arguments. `use_common_time` is probably better as a keyword argument, so that's why I put it after `*args`

**Comment by khider** [comment]
Should I merge this?

**Comment by CommonClimate** [comment]
Yes. Headed into lecture now

Julien Emile-Geay,  professor
University of Southern California


On Mar 1, 2023, at 07:47, Deborah Khider ***@***.***> wrote:

﻿

Should I merge this?

**Pull request merged**
