### PR TITLE
Add some doc strings

### PR DESCRIPTION
**Pull request by kcpevey**
* Add doc strings to new methods
* Add examples as doc test

Also while waiting for tests to run I added a few "close figs"

### CODE REVIEW

**Comment by kcpevey** [comment]
There were some other doc strings that I could have added but I was concerned about working on top of @MarcoGorelli ad @CommonClimate on changing code.

**Comment by CommonClimate** [comment]
Good thinking @kcpevey . Is this ready for review, then, or will you open another PR once we're done with code edits, so you can put in the other docstrings?

**Review by CommonClimate — APPROVED** [review]
Looks good! I might just change "pyleo_series" to "ts" in the `load_dataset()` docstring, as we typically use that moniker for a Series, the same way pandas uses "df" for dataframe, even though anything is allowed.

**Comment by CommonClimate** [comment]
Also, just saw the docstring for `sel()`, which is nice and comprehensive. In terms of the screen output, though, it won't look like this anymore:
```{'log': ({0: 'clean_ts', 'applied': True, 'verbose': False},
                {2: 'clean_ts', 'applied': True, 'verbose': False})}```
                
It should be:

```{'log': ({0: 'dropna', 'applied': True, 'verbose': True},
         {1: 'sort_ts', 'direction': 'ascending'})}```

Sorry to change this on you. So I guess this way of making docstrings does not take changes in the codebase into account. That is an argument for using ipython directives...

**Comment by kcpevey** [comment]
Yes, this is ready for review. I can open another if I need to.

**Review by CommonClimate — APPROVED** [review]

**Comment by CommonClimate** [comment]
OK, I like that plan. Re: docstrings, the SeriesResampler will need a lot of explanation. Honestly, I still don't understand exactly how it works, and I doubt our users will. If applicable, you can link to [this](https://pandas.pydata.org/docs/user_guide/timeseries.html#resampling) but also important to explain the differences. Or we may need a whole tutorial about how to use that class, preferably as a notebook in the paleopandas repo. We can then fold it into our [PyleoTutorials](http://linked.earth/PyleoTutorials/intro.html).

**Pull request merged**
