### PR TITLE
MulEnsGeoSeries stackplot

### PR DESCRIPTION
**Pull request by alexkjames**
Adds stackplot functionality to MulEnsGeoSeries class, alongside unit tests. Addresses #579

### CODE REVIEW

**Review by CommonClimate — CHANGES_REQUESTED** [review]
Hi @alexkjames, thanks for doing this. 
I only tested the docstring example, which is fine, though it doesn't show much about how to customize the plot. Maybe refer to `MultipleSeries.stackplot()` in the "See Also" section so interested users can see how it's done?

**Comment by CommonClimate** [comment]
I like the new `style` feature. Can you make sure users can pass ensemble plot options as they would to `EnsembleSeries.plot()`?  In particular, some users will want to adjust  `shade_alpha` for `plot_envelope()` and `num_traces` for `plot_traces()`

**Comment by alexkjames** [comment]
> I like the new `style` feature. Can you make sure users can pass ensemble plot options as they would to `EnsembleSeries.plot()`? In particular, some users will want to adjust `shade_alpha` for `plot_envelope()` and `num_traces` for `plot_traces()`

These are currently adjustable via the `plot_kwargs` option, I'm a bit hesitant to include exposed arguments for the plotting methods, since there usage will depend on what `style` is set to. I've include a docstring example of using the `plot_kwargs` argument to make these adjustments, does that suffice or would you still like certain arguments to be exposed?

**Review by CommonClimate — APPROVED** [review]
Thanks for the changes! Good to go!

**Pull request merged**
