### PR TITLE
add auto_time_params arg to series init

### PR DESCRIPTION
**Pull request by alexkjames**
Address Issue #469 

I've just added an `auto_time_params` argument to Series, and nested the time name/unit logic within an `if` statement that relies on the value of `auto_time_params`.

This is the simplest fix to issue #469. We discussed having a way to switch a series in between having auto and not auto time params, but I'm not sure this is necessary. If it is I'm happy to create a function to do so, though I might suggest waiting until such a thing is requested/it becomes clear that we need it since creating Series objects is already pretty straightforward. 

Was there anything else we wanted to do here?

### CODE REVIEW

**Comment by CommonClimate** [comment]
Thanks for doing this @alexkjames ! I'll review this week.

**Comment by CommonClimate** [comment]
I seem to remember @khider wanting  `auto_time_params = False` by default. Did I misremember?

**Comment by khider** [comment]
I think we should have it True for a while so it mimics the behavior of the current version and have a warning that it will be set to False in subsequent releases.

**Comment by CommonClimate** [comment]
That sounds good. @alexkjames can you do that and update the PR?

**Review by CommonClimate — APPROVED** [review]

**Comment by CommonClimate** [comment]
closes #469

**Pull request merged**
