### PR TITLE
add test for resampling over long periods

### PR DESCRIPTION
**Pull request by MarcoGorelli**

### CODE REVIEW

**Comment by CommonClimate** [comment]
Hi @MarcoGorelli, `test_resample_long_periods` looks like a very minimal test (2 values). Is that sufficient to judge that the code is working properly?  If I understand things right, the test is taking `dataframe_dt()`, which generates a series of 5 values (0 to 4) at yearly intervals, reindexes them according to 3 rules (1 Ga, 1 Ma and 2 ka), and makes sure that the resampled average is correct. However, I don't understand: 
- why the expected values are [0 2.5], as the mean value of  dataframe_dt() is 2.0.
- why there is a test on metadata that uses SOI metadata. Is it to make the the rule is properly added to the series' label?

The docstring is a little terse. What do you mean by "The offset string or object representing target conversion"? Can you link to pandas pages that explain how to use that? I added a docstring example that should produce this output: 

LR04_resample5k

other than that, it looks good.

**Comment by CommonClimate** [comment]
Additional question on this, which popped up in #330 . I notice that the pandas Resampler class has an [interpolate](https://pandas.pydata.org/docs/reference/api/pandas.core.resample.Resampler.interpolate.html) method, but that does not appear to be available to `pyleo.SeriesResampler()`. Would it be hard to make that work? We just figured out it would save us a bunch of headaches to apply interpolation via pandas instead of the more limited `scipy.interpolate.interp1d`, which can't deal with NaNs.

**Comment by MarcoGorelli** [comment]
hey @CommonClimate 

> Is that sufficient to judge that the code is working properly? 

not really, but it's tested in pandas itself, here it's just to check that the convenience method works fine

thanks for updating the docstring!

I'll take a look at interpolate, I think it should work

**Comment by MarcoGorelli** [comment]
> why the expected values are [0 2.5], as the mean value of dataframe_dt() is 2.0.

**Comment by MarcoGorelli** [comment]
> why the expected values are [0 2.5], as the mean value of dataframe_dt() is 2.0.

it's because of how it's bucketing the data - the values are [0, 1, 2, 3, 4], and `0` ends up in its own bucket, and the others in the other one, and so the means are `0` and `2.5`

**Comment by MarcoGorelli** [comment]
> why there is a test on metadata that uses SOI metadata. Is it to make the the rule is properly added to the series' label?

yeah it's just to check that it roundtrips

I've added a link to the pandas docs

Regarding interpolate - it looks like you already remove null values during instantiation

https://github.com/LinkedEarth/Pyleoclim_util/blob/59cce2b7398e39db16b16c0fa01acbd5f63b6eaf/pyleoclim/core/series.py#L2174

, could you show an example of how you end up with missing values and would like to interpolate them please? Would also prefer to keep that to a separate issue if possible

@CommonClimate anything else need doing here?

**Comment by CommonClimate** [comment]
Hi @MarcoGorelli , sure I'll merge this now and we'll open a new issue in the paleopandas repo so I can tag you there.

**Pull request merged**
