### PR TITLE
Fix Issue #180 

### PR DESCRIPTION
**Pull request by alexkjames**
Updated the default behavior of summary_plot to:

- Obtain the psd directly from the scalogram (uses wwz for both, can be overridden by user)
- Preprocess time series before generating scalogram and psd (standardize then detrend using default pyleoclim methods)

Note that the preprocessed time series is not used in the plot, only to generate the scal and psd

Also updated summary plot unit tests, added a new one to test different possible combinations of passing psd and scal objects

### CODE REVIEW

**Comment by CommonClimate** [comment]
Thanks Alex. Can you post a summary_plot figure here so we can all be satisfied that this is fixed?

**Comment by alexkjames** [comment]
figures

An example with significance testing. If no significance testing is done then the psd is pulled from the scalogram. We could add in additional arguments to specificy scalogram significance testing vs psd significance testing but I'm not sure if thats valuable or if it would simply add more clutter to the arguments

**Comment by CommonClimate** [comment]
Thanks @alexkjames ; can you clarify if significance testing is done differently for the PSD and the scalogram? It would seem that the method needs to use the exact same noise realizations on both to be meaningful.

 In any case, I think of such a plot as an exploratory tool; we should warn users in the docstring that if they are after fine points of spectral detection, this likely isn't the best option for them.

**Comment by alexkjames** [comment]
.signif_test is run on both of them separately, so I dont believe they're currently sharing a noise realization. @fzhu2e might be able to weigh in on whether this is currently doable. from what I understand pyleoclim doesn't currently have that functionality. I can include a warning in the docstring on the exploratory nature of the function

**Comment by fzhu2e** [comment]
> .signif_test is run on both of them separately, so I dont believe they're currently sharing a noise realization. @fzhu2e might be able to weigh in on whether this is currently doable. from what I understand pyleoclim doesn't currently have that functionality. I can include a warning in the docstring on the exploratory nature of the function

You're right. The noise realizations are currently separate. To reuse the scalograms of the noise realizations in  `.wavelet().signif_test()`, we need to save the `Scalogram` output, which is currently not saved.

In `Scalogram.signif_test()`, we have
```
        if number == 0:
            return self

        new = self.copy()
        surr = self.timeseries.surrogates(
            number=number, seed=seed, method=method, settings=settings
        )
        surr_scal = surr.wavelet(method=self.wave_method, settings=self.wave_args)

        if len(qs) > 1:
            raise ValueError('qs should be a list with size 1!')

        new.signif_qs = surr_scal.quantiles(qs=qs)
        new.signif_method = method

        return new
```
So here, we need to add one line`new.signif_scals = surr_scal` before `return new`, and then use this in the later `.spectral().signif_test()`  with in the form of `.spectral(scalogram=scal)`, which will also save computing time. 

Hope this helps.

**Comment by alexkjames** [comment]
@CommonClimate I'll create a new issue for this and assign myself to it, it seems like a functionality that might be worth having down the line

**Comment by CommonClimate** [comment]
Sounds good. I would just make the export of surrogate scalograms an optional feature, because a) it will considerably weigh down memory and b) few users will want it.  So only activate with `Scalogram.signif_test(export_scal = True)`, or something like that

**Pull request merged**
