### PR TITLE
Ensemblegeoseries + MCPCA

### PR DESCRIPTION
**Pull request by alexkjames**
Adds several new objects to faciliate MCPCA analysis on age uncertain paleo records.

New class include:

* EnsembleGeoSeries - An EnsembleSeries object for GeoSeries objects
* MulEnsGeoSeries - An object to contain multiple EnsembleGeoSeries objects
* MulMultivarDecomp - An object to store and plot the output of MCPCA applied to MulEnsGeoSeries objects

Contains unit tests for all new functions. Also includes a dashboard method for EnsembleGeoSeries objects, and several useful classmethods for generating ensemble and ensemblegeoseries objects from age arrays.

### CODE REVIEW

**Review by khider — COMMENTED** [review]
You need to have some example on how to create the object, especially for the classmethod portion

**Comment by CommonClimate** [comment]
Also, I thought we had agreed on `MulMultivarDecomp` being `EnsMultivarDecomp', since it's the ensemble part that we emphasize, and Multivar is already Mul. Wow, that was a mouthful...

**Comment by alexkjames** [comment]
> Also, I thought we had agreed on `MulMultivarDecomp` being `EnsMultivarDecomp', since it's the ensemble part that we emphasize, and Multivar is already Mul. Wow, that was a mouthful...

You're right, I left my post it where I wrote that down in the office and, since I haven't been back since we had that meeting, just winged it. I updated the class name in the most recent commit above this comment.

**Comment by CommonClimate** [comment]
Great, thank you!

**Review by khider — APPROVED** [review]

**Pull request merged**
